package StockApp;

import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Matias Silva
 */
public class altaPuestos extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public altaPuestos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        altaButton = new javax.swing.JButton();
        descriptionText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        altaVigenciaCheck = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        verEquiposButton = new javax.swing.JMenu();
        verPartesButton = new javax.swing.JMenu();
        verSucursalesButton = new javax.swing.JMenu();
        verLocalidadesButton = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        altaEquiposButton = new javax.swing.JMenuItem();
        altaPartesButton = new javax.swing.JMenuItem();
        altaLocalidadesButton = new javax.swing.JMenuItem();
        altaSucursalesButton = new javax.swing.JMenuItem();
        altaPuestosButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NCR stock manager");
        setName("NCR stock manager"); // NOI18N

        jLabel1.setText("Descripcion:");

        altaButton.setText("Dar de alta");
        altaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Imagen(opcional):");

        altaVigenciaCheck.setSelected(true);
        altaVigenciaCheck.setText("Vigente");
        altaVigenciaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaVigenciaCheckActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Formulario de nuevo Equipo");

        verEquiposButton.setText("Equipos");
        jMenuBar1.add(verEquiposButton);

        verPartesButton.setText("Partes");
        jMenuBar1.add(verPartesButton);

        verSucursalesButton.setText("Sucursales");
        jMenuBar1.add(verSucursalesButton);

        verLocalidadesButton.setText("Localidades");
        jMenuBar1.add(verLocalidadesButton);

        jMenu5.setText("Dar de alta");

        altaEquiposButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        altaEquiposButton.setText("Equipos");
        altaEquiposButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaEquiposButtonActionPerformed(evt);
            }
        });
        jMenu5.add(altaEquiposButton);

        altaPartesButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        altaPartesButton.setText("Partes");
        jMenu5.add(altaPartesButton);

        altaLocalidadesButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        altaLocalidadesButton.setText("Localidades");
        jMenu5.add(altaLocalidadesButton);

        altaSucursalesButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        altaSucursalesButton.setText("Sucursales");
        altaSucursalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaSucursalesButtonActionPerformed(evt);
            }
        });
        jMenu5.add(altaSucursalesButton);

        altaPuestosButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        altaPuestosButton.setText("Puestos");
        jMenu5.add(altaPuestosButton);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(altaButton)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionText)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(altaVigenciaCheck))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 248, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(altaVigenciaCheck)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(altaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaEquiposButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaEquiposButtonActionPerformed
        this.setVisible(false);
        new altaPuestos().setVisible(true);
    }//GEN-LAST:event_altaEquiposButtonActionPerformed

    private void altaSucursalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaSucursalesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altaSucursalesButtonActionPerformed

    private void altaVigenciaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaVigenciaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altaVigenciaCheckActionPerformed

    private void altaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaButtonActionPerformed
        String desText = descriptionText.getText();
        String actBool = "obsolete";
        if (altaVigenciaCheck.isSelected()){
            actBool = "active";
        }
                
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydatabase", "root", "matias18");
            Statement stmt = con.createStatement();
            String query = "INSERT INTO `mydatabase`.`equipo` (`descripcionEquipo`,`vigencia`) VALUES ('" + desText + "','" + actBool +"');";
            stmt.execute(query);
            JOptionPane.showMessageDialog(this, "El nuevo equipo ha sido agregado a la base de datos con exito");
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_altaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaButton;
    private javax.swing.JMenuItem altaEquiposButton;
    private javax.swing.JMenuItem altaLocalidadesButton;
    private javax.swing.JMenuItem altaPartesButton;
    private javax.swing.JMenuItem altaPuestosButton;
    private javax.swing.JMenuItem altaSucursalesButton;
    private javax.swing.JCheckBox altaVigenciaCheck;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu verEquiposButton;
    private javax.swing.JMenu verLocalidadesButton;
    private javax.swing.JMenu verPartesButton;
    private javax.swing.JMenu verSucursalesButton;
    // End of variables declaration//GEN-END:variables

}
